spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sampledb
    username: spring
    password: spring
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 50
    max-wait: 10000
    max-idle: 10
    min-idle: 8
    test-on-borrow: true
    validation-query: select 1

mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
